# Generated by Django 6.0.1 on 2026-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='puntos',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos de Sabiduría'),
        ),
    ]
