# Generated by Django 5.2.17 on 2026-09-10 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_perfil_puntos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Logro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(help_text="Ej: primer-paso", unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "icono",
                    models.CharField(
                        choices=[
                            ("🏅", "Medalla"),
                            ("🎖️", "Condecoración"),
                            ("🥇", "Oro"),
                            ("🥈", "Plata"),
                            ("🥉", "Bronce"),
                            ("⭐", "Estrella"),
                            ("🌟", "Estrella brillante"),
                            ("💎", "Diamante"),
                            ("👑", "Corona"),
                            ("🔥", "Racha"),
                            ("📚", "Libro"),
                            ("🎓", "Graduación"),
                            ("🏆", "Trofeo"),
                            ("🧠", "Cerebro"),
                            ("✍️", "Escritura"),
                            ("🎯", "Objetivo"),
                            ("🚀", "Cohete"),
                            ("🌱", "Brote"),
                            ("🌳", "Árbol"),
                        ],
                        default="🏅",
                        max_length=5,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("puntos", "Puntos"),
                            ("lecciones", "Lecciones completadas"),
                            ("cursos", "Cursos inscritos"),
                            ("racha", "Racha de días"),
                            ("especial", "Logro especial"),
                        ],
                        default="especial",
                        max_length=20,
                    ),
                ),
                (
                    "umbral",
                    models.IntegerField(
                        default=1, help_text="Cantidad necesaria para desbloquear"
                    ),
                ),
                (
                    "puntos_bonus",
                    models.IntegerField(
                        default=0, help_text="Puntos extra al desbloquear"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Logro",
                "verbose_name_plural": "Logros",
                "ordering": ["tipo", "umbral"],
            },
        ),
        migrations.CreateModel(
            name="LogroUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_desbloqueo", models.DateTimeField(auto_now_add=True)),
                (
                    "logro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.logro"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro de usuario",
                "verbose_name_plural": "Logros de usuarios",
                "ordering": ["-fecha_desbloqueo"],
                "unique_together": {("usuario", "logro")},
            },
        ),
    ]
