[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = test_*.py tests.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --tb=short
    --strict-markers
    --disable-warnings
    --reuse-db
    -p no:cacheprovider
testpaths = tests
markers =
    slow: tests lentos
    integration: tests de integracion
