# Generated by Django 6.0.1 on 2026-01-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la frase/modismo')),
                ('pais_origen', models.CharField(max_length=100, verbose_name='País donde se usa')),
                ('explicacion', models.TextField(verbose_name='Significado y contexto cultural')),
                ('ejemplo_uso', models.TextField(verbose_name='Ejemplo en una frase real')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Lecciones',
            },
        ),
    ]
