# Generated by Django 6.0.1 on 2026-01-10 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Lecciones'},
        ),
        migrations.AddField(
            model_name='leccion',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden de la lección'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('idioma', models.CharField(choices=[('ES', 'Español'), ('EN', 'English'), ('ZH', 'Chino'), ('HI', 'Hindi'), ('FR', 'Français'), ('AR', 'Árabe'), ('BN', 'Bengalí'), ('PT', 'Portugués'), ('RU', 'Ruso'), ('UR', 'Urdu')], max_length=2)),
                ('nivel', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2 (HASC2)')], max_length=2)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.materia')),
            ],
        ),
        migrations.AddField(
            model_name='leccion',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='courses.curso'),
        ),
    ]
