# Generated by Django 6.0.1 on 2026-01-13 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_materia_alter_leccion_options_leccion_orden_curso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='ejercicio_datos',
            field=models.JSONField(blank=True, default=dict, help_text='Datos JSON: pregunta, respuesta, explicacion'),
        ),
        migrations.AddField(
            model_name='leccion',
            name='video_explicativo',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.CreateModel(
            name='ProgresoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.leccion')),
            ],
            options={
                'verbose_name': 'Progreso de Estudiante',
                'verbose_name_plural': 'Progresos de Estudiantes',
                'unique_together': {('estudiante', 'leccion')},
            },
        ),
    ]
