# Generated by Django 5.2.17 on 2026-09-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_leccion_ejercicio_datos_leccion_video_explicativo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecursoInteractivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                (
                    "archivo_html",
                    models.CharField(
                        help_text="Nombre del archivo dentro de templates/ejercicios_completos-lengua-castellana/",
                        max_length=500,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("flota", "Flota temática"),
                            ("flashcards", "Flashcards + Quiz"),
                            ("cuaderno", "Cuaderno"),
                            ("app", "App interactiva"),
                            ("tecnica", "Técnicas numeradas"),
                            ("archivo_vector", "Archivo de Vector"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Recurso interactivo",
                "verbose_name_plural": "Recursos interactivos",
                "ordering": ["tipo", "orden", "titulo"],
            },
        ),
    ]
