# Generated by Django 5.2.17 on 2026-09-10 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_inscripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=20, unique=True)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_completado",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("emitido", "Emitido"), ("revocado", "Revocado")],
                        default="emitido",
                        max_length=20,
                    ),
                ),
                ("puntos_obtenidos", models.IntegerField(default=0)),
                (
                    "calificacion",
                    models.CharField(blank=True, default="Aprobado", max_length=50),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="courses.curso",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-fecha_emision"],
                "unique_together": {("estudiante", "curso")},
            },
        ),
    ]
