# Generated by Django 5.2.17 on 2026-09-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_certificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="recursointeractivo",
            name="actualizado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="recursointeractivo",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Color principal extraído del HTML (hex)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recursointeractivo",
            name="descripcion",
            field=models.TextField(
                blank=True, help_text="Descripción extraída del HTML"
            ),
        ),
        migrations.AddField(
            model_name="recursointeractivo",
            name="num_tecnicas",
            field=models.IntegerField(
                default=0, help_text="Número de técnicas/ejercicios, si aplica"
            ),
        ),
        migrations.AddField(
            model_name="recursointeractivo",
            name="subtitulo",
            field=models.CharField(
                blank=True,
                help_text="Frase corta que describe el recurso",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="recursointeractivo",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Etiquetas separadas por coma", max_length=300
            ),
        ),
    ]
