# Generated by Django 5.2.17 on 2026-09-10 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_recursointeractivo_actualizado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "descripcion",
                    models.TextField(help_text="Instrucciones para el estudiante"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("texto", "Respuesta escrita"),
                            ("archivo", "Subir archivo"),
                            ("enlace", "Enlace"),
                            ("codigo", "Código"),
                        ],
                        default="texto",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicada", "Publicada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="publicada",
                        max_length=20,
                    ),
                ),
                ("fecha_limite", models.DateTimeField(blank=True, null=True)),
                ("puntaje_maximo", models.IntegerField(default=100)),
                ("orden", models.IntegerField(default=0)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="courses.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["orden", "-creada"],
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("entregada", "Entregada"),
                            ("calificada", "Calificada"),
                            ("devuelta", "Devuelta para revisión"),
                        ],
                        default="entregada",
                        max_length=20,
                    ),
                ),
                (
                    "contenido",
                    models.TextField(
                        blank=True, help_text="Respuesta escrita o comentario"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="entregas/"),
                ),
                ("enlace", models.URLField(blank=True)),
                ("calificacion", models.IntegerField(blank=True, null=True)),
                (
                    "retroalimentacion",
                    models.TextField(blank=True, help_text="Comentarios del profesor"),
                ),
                ("fecha_entrega", models.DateTimeField(auto_now_add=True)),
                ("fecha_calificacion", models.DateTimeField(blank=True, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="courses.tarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
                "ordering": ["-fecha_entrega"],
                "unique_together": {("tarea", "estudiante")},
            },
        ),
    ]
