# Generated by Django 5.2.17 on 2026-09-10 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_tarea_entrega"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicada", "Publicada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="publicada",
                        max_length=20,
                    ),
                ),
                (
                    "puntaje_maximo",
                    models.IntegerField(default=100, help_text="Puntaje total posible"),
                ),
                (
                    "puntaje_aprobacion",
                    models.IntegerField(
                        default=60, help_text="Puntaje mínimo para aprobar"
                    ),
                ),
                (
                    "intentos_maximos",
                    models.IntegerField(
                        default=3, help_text="Cuántas veces puede intentarlo"
                    ),
                ),
                (
                    "tiempo_limite_minutos",
                    models.IntegerField(blank=True, default=30, null=True),
                ),
                ("aleatorizar_preguntas", models.BooleanField(default=False)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                ("actualizada", models.DateTimeField(auto_now=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="courses.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "ordering": ["curso", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="IntentoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje", models.IntegerField(default=0)),
                ("aprobado", models.BooleanField(default=False)),
                ("completado", models.BooleanField(default=False)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_evaluacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos",
                        to="courses.evaluacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de evaluación",
                "verbose_name_plural": "Intentos de evaluación",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="PreguntaEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(help_text="Enunciado de la pregunta")),
                (
                    "explicacion",
                    models.TextField(
                        blank=True, help_text="Explicación de la respuesta correcta"
                    ),
                ),
                (
                    "puntaje",
                    models.IntegerField(
                        default=10, help_text="Puntos que vale esta pregunta"
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="courses.evaluacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "ordering": ["evaluacion", "orden"],
            },
        ),
        migrations.CreateModel(
            name="OpcionRespuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500)),
                ("es_correcta", models.BooleanField(default=False)),
                ("orden", models.IntegerField(default=0)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="courses.preguntaevaluacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de respuesta",
                "verbose_name_plural": "Opciones de respuesta",
                "ordering": ["pregunta", "orden"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaIntento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "intento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="courses.intentoevaluacion",
                    ),
                ),
                (
                    "opcion_elegida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.opcionrespuesta",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.preguntaevaluacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta del intento",
                "verbose_name_plural": "Respuestas del intento",
                "unique_together": {("intento", "pregunta")},
            },
        ),
    ]
