# Generated by Django 5.2.11 on 2026-10-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_evaluacion_intentoevaluacion_preguntaevaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaevaluacion',
            name='pares_json',
            field=models.JSONField(blank=True, default=list, help_text='Lista de pares: [{"izq": "...", "der": "..."}, ...]'),
        ),
        migrations.AddField(
            model_name='preguntaevaluacion',
            name='respuesta_corta',
            field=models.CharField(blank=True, help_text='Respuestas validas separadas por | (ej: haber|a ver)', max_length=300),
        ),
        migrations.AddField(
            model_name='preguntaevaluacion',
            name='tipo',
            field=models.CharField(choices=[('unica', 'Opcion unica'), ('multiple', 'Opcion multiple'), ('vf', 'Verdadero / Falso'), ('corta', 'Respuesta corta'), ('emparejar', 'Emparejamiento')], default='unica', max_length=20),
        ),
        migrations.AlterField(
            model_name='preguntaevaluacion',
            name='explicacion',
            field=models.TextField(blank=True, help_text='Explicacion de la respuesta correcta'),
        ),
    ]
