# Generated by Django 5.2.11 on 2026-10-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_preguntaevaluacion_pares_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='recursos_relacionados',
            field=models.ManyToManyField(blank=True, help_text='Recursos interactivos complementarios para este curso', related_name='cursos_relacionados', to='courses.recursointeractivo'),
        ),
        migrations.AddField(
            model_name='leccion',
            name='recursos_complementarios',
            field=models.ManyToManyField(blank=True, help_text='Recursos interactivos para practicar esta leccion', related_name='lecciones_relacionadas', to='courses.recursointeractivo'),
        ),
    ]
