# Generated by Django 5.2.11 on 2026-10-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_curso_recursos_relacionados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='recursos_complementarios',
            field=models.ManyToManyField(blank=True, help_text='Recursos interactivos para practicar esta evaluacion', related_name='evaluaciones_relacionadas', to='courses.recursointeractivo'),
        ),
    ]
